# ------------------------------------------------------------------------------
# Builder Image
# ------------------------------------------------------------------------------
FROM golang:1.14 AS build

WORKDIR /go/src/github.com/figment-networks/indexer-manager/

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY .git .git
COPY ./Makefile ./Makefile
COPY ./cmd/common ./cmd/common
COPY ./cmd/manager-migration ./cmd/manager-migration


ENV CGO_ENABLED=0
ENV GOARCH=amd64
ENV GOOS=linux

RUN \
  GO_VERSION=$(go version | awk {'print $3'}) \
  GIT_COMMIT=$(git rev-parse HEAD) \
  make build-manager-migration

# ------------------------------------------------------------------------------
# Target Image
# ------------------------------------------------------------------------------
FROM alpine:3.10 AS release

WORKDIR /app/migration

COPY --from=build /go/src/github.com/figment-networks/indexer-manager/migration /app/migration/migration
COPY --from=build /go/src/github.com/figment-networks/indexer-manager/cmd/manager-migration/migrations/ /app/migration/migrations/
RUN chmod a+x ./migration
CMD ["./migration"]
