# ------------------------------------------------------------------------------
# Builder Image
# ------------------------------------------------------------------------------
FROM golang:1.14 AS build

WORKDIR /go/src/github.com/figment-networks/indexer-manager/

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY .git .git
COPY ./Makefile ./Makefile
COPY ./scheduler ./scheduler
COPY ./structs  ./structs
COPY ./cmd/common ./cmd/common
COPY ./cmd/scheduler ./cmd/scheduler

ENV CGO_ENABLED=0
ENV GOARCH=amd64
ENV GOOS=linux

RUN \
  GO_VERSION=$(go version | awk {'print $3'}) \
  GIT_COMMIT=$(git rev-parse HEAD) \
  make build-scheduler

# ------------------------------------------------------------------------------
# Target Image
# ------------------------------------------------------------------------------
FROM alpine:3.10 AS release

WORKDIR /app/scheduler
COPY --from=build /go/src/github.com/figment-networks/indexer-manager/scheduler_bin /app/scheduler/scheduler
RUN chmod a+x ./scheduler
CMD ["./scheduler"]
