# ------------------------------------------------------------------------------
# Builder Image
# ------------------------------------------------------------------------------
FROM golang:1.14 AS build

WORKDIR /go/src/github.com/figment-networks/cosmos-indexer/

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY .git .git
COPY ./Makefile ./Makefile
COPY ./worker ./worker
COPY ./structs ./structs
COPY ./cmd/worker_terra ./cmd/worker_terra

ENV CGO_ENABLED=0
ENV GOARCH=amd64
ENV GOOS=linux

RUN \
  GO_VERSION=$(go version | awk {'print $3'}) \
  GIT_COMMIT=$(git rev-parse HEAD) \
  make build-terra

# ------------------------------------------------------------------------------
# Target Image
# ------------------------------------------------------------------------------
FROM alpine:3.10 AS release

WORKDIR /app/terra
COPY --from=build /go/src/github.com/figment-networks/cosmos-indexer/worker_terra_bin /app/terra/worker
RUN chmod a+x ./worker
CMD ["./worker"]
