# ------------------------------------------------------------------------------
# Builder Image
# ------------------------------------------------------------------------------
FROM golang:1.14 AS buildSchedulerMigration

WORKDIR /go/src/github.com/figment-networks/cosmos-indexer/

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY .git .git
COPY ./Makefile ./Makefile
COPY ./cmd/scheduler-migration ./cmd/scheduler-migration

ENV CGO_ENABLED=0
ENV GOARCH=amd64
ENV GOOS=linux

RUN \
  GO_VERSION=$(go version | awk {'print $3'}) \
  GIT_COMMIT=$(git rev-parse HEAD) \
  make build-scheduler-migration

# ------------------------------------------------------------------------------
# Target Image
# ------------------------------------------------------------------------------
FROM alpine:3.10 AS releaseSchedulerMigration

WORKDIR /app/migration

COPY --from=buildSchedulerMigration /go/src/github.com/figment-networks/cosmos-indexer/scheduler_migration_bin /app/migration/scheduler_migration
COPY --from=buildSchedulerMigration /go/src/github.com/figment-networks/cosmos-indexer/cmd/scheduler-migration/migrations/ /app/migration/migrations/
RUN chmod a+x ./scheduler_migration
CMD ["./scheduler_migration"]
