version: "3.7"

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  postgresdatabase:

services:
  postgresdatabase:
    image: timescale/timescaledb:latest-pg10
    networks:
      - internal
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cosmos
      POSTGRES_PASSWORD: cosmos
      POSTGRES_DB: cosmos
    volumes:
      - postgresdatabase:/var/lib/postgresql/data/

  migrate:
    build:
      context: .
      dockerfile: ./Dockerfile.migration
    networks:
      - internal
    environment:
      DATABASE_URL: postgres://cosmos:cosmos@database/cosmos?sslmode=disable
    depends_on:
      - postgresdatabase
